// <auto-generated />
namespace AdmissionsWebsite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IEnumerableGender : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IEnumerableGender));
        
        string IMigrationMetadata.Id
        {
            get { return "202104111827365_IEnumerableGender"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
